# Generated by Django 6.0.2 on 2026-02-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
