# Generated by Django 6.0.2 on 2026-03-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contactform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
