# Generated by Django 6.0.2 on 2026-03-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contactform_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
