# Generated by Django 6.0.2 on 2026-03-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contactform_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Sobre nó'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Forms de Contato'},
        ),
    ]
